/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { OutlinerRequestBuilder } from './outliner/';
import { BaseRequestBuilder, type RequestAdapter } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export class ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The Outliner property
     */
    public get outliner(): OutlinerRequestBuilder {
        return new OutlinerRequestBuilder(this.pathParameters, this.requestAdapter);
    }
    /**
     * Instantiates a new ApiRequestBuilder and sets the default values.
     * @param pathParameters The raw url or the Url template parameters for the request.
     * @param requestAdapter The request adapter to use to execute the requests.
     */
    public constructor(pathParameters: Record<string, unknown> | string | undefined, requestAdapter: RequestAdapter) {
        super(pathParameters, requestAdapter, "{+baseurl}/api", (x, y) => new ApiRequestBuilder(x, y));
    }
}
/* tslint:enable */
/* eslint-enable */
